---
name: Size Limit Increase Request
title: >-
  Limit Request: PROJECT_NAME - 000 MB
description: >-
  You want to request a file size limit or project total size
  limit increase
labels: limit request

body:
- type: markdown
  attributes:
    value: |
      If you can't upload your project's release to PyPI because you're
      hitting the upload file size limit or the project total size
      limit, we can sometimes increase your limit.

      If you're hitting the upload file size limit, make sure you've
      uploaded at least one release for the project that's under the
      limit (a developmental release version number is fine).

- type: input
  attributes:
    label: Project URL
    description: |
      Provide a link to the PyPI page for the project in question,
      i.e. https://pypi.org/project/<PROJECT_NAME>

      Please **update "PROJECT_NAME"** in the issue title as well.
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Does this project already exist?
    description: |
      This project **MUST EXIST** for an increased limit to be set.
      You can create an empty 0.0.0 release and delete it immediately if
      it doesn't already exist.
    options:
    - label: "Yes"  # should be a str but YAML parses unwrapped yes/no as bool
      required: true

- type: dropdown
  attributes:
    label: Which limit do you want increased?
    description: >-
      There are 2 kinds of size limits on projects.
    options:
    - per release file
    - total project size
  validations:
    required: true

- type: input
  attributes:
    label: New limit
    description: |
      Please specify a new size limit, in megabytes, that you want.

      Please **update "000 MB"** in the issue title as well.
  validations:
    required: true

- type: dropdown
  attributes:
    label: Which indexes
    description: >-
      Which index/indexes you need the increase for?
      (PyPI, Test PyPI, or both)
    multiple: true
    options:
    - PyPI
    - TestPyPI
  validations:
    required: true

- type: textarea
  attributes:
    label: Reasons for the request
    description: |
      A description of the project, and the reason for the
      additional size.

      If you expect your release sizes/total project size to increase in
      the future, mention it here.
  validations:
    required: true


- type: checkboxes
  attributes:
    label: Code of Conduct
    description: |
      Read the [PSF Code of Conduct][CoC] first.

      [CoC]: https://github.com/pypa/.github/blob/main/CODE_OF_CONDUCT.md
    options:
    - label: I agree to follow the PSF Code of Conduct
      required: true
...
